# Generated by Django 5.0.13 on 2025-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lecturerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
