# Generated by Django 5.0.13 on 2025-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_verification_code_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
