# Generated by Django 5.0.13 on 2025-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subject_unique_together_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
