# Generated by Django 5.0.13 on 2025-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lecturerprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('sw_engineering', 'Software Engineering'), ('computer_science', 'Computer Science'), ('electronic_engineering', 'Electronic Engineering')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=1),
        ),
    ]
