# Generated by Django 4.2.23 on 2025-06-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('מדעי המחשב', 'מדעי המחשב'), ('הנדסת תוכנה', 'הנדסת תוכנה'), ('הנדסת אלקטרוניקה', 'הנדסת אלקטרוניקה'), ('sw_engineering', 'Software Engineering'), ('computer_science', 'Computer Science'), ('electronic_engineering', 'Electronic Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'is_lecturer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('מדעי המחשב', 'מדעי המחשב'), ('הנדסת תוכנה', 'הנדסת תוכנה'), ('הנדסת אלקטרוניקה', 'הנדסת אלקטרוניקה'), ('sw_engineering', 'Software Engineering'), ('computer_science', 'Computer Science'), ('electronic_engineering', 'Electronic Engineering')], max_length=50),
        ),
    ]
