# Generated by Django 4.2.23 on 2025-06-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='שם מלא', max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('מדעי המחשב', 'מדעי המחשב'), ('הנדסת תוכנה', 'הנדסת תוכנה'), ('הנדסת אלקטרוניקה', 'הנדסת אלקטרוניקה')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('מדעי המחשב', 'מדעי המחשב'), ('הנדסת תוכנה', 'הנדסת תוכנה'), ('הנדסת אלקטרוניקה', 'הנדסת אלקטרוניקה')], max_length=50),
        ),
    ]
