# Generated by Django 4.2.23 on 2025-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_full_name_alter_subject_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('secretary', 'Secretary')], default='student', max_length=20),
        ),
    ]
