# Generated by Django 5.0.13 on 2025-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
