# Generated by Django 5.0.13 on 2025-06-10 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='שם מלא')),
                ('reporter_email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('error_type', models.CharField(choices=[('syntax', 'שגיאת תחביר (Syntax)'), ('logic', 'שגיאה לוגית'), ('runtime', 'שגיאת ריצה'), ('ui', 'בעיה בממשק משתמש (UI/UX)'), ('performance', 'בעיית ביצועים'), ('login', 'בעיית התחברות (לא נכנס למערכת)'), ('notification', 'התראות לא נשלחות'), ('other', 'אחר')], max_length=20, verbose_name='סוג השגיאה')),
                ('error_description', models.TextField(verbose_name='תיאור השגיאה')),
                ('error_media', models.FileField(blank=True, null=True, upload_to='error_reports/', verbose_name='תיעוד השגיאה')),
                ('urgency', models.CharField(choices=[('low', 'נמוכה (לא מפריעה לעבודה)'), ('medium', 'בינונית (מפריעה חלקית)'), ('high', 'גבוהה (מונע עבודה)'), ('critical', 'דחוף! (המערכת לא עובדת)')], default='medium', max_length=10, verbose_name='דחיפות הטיפול')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('in_progress', 'בטיפול'), ('resolved', 'נפתר'), ('closed', 'סגור')], default='pending', max_length=15, verbose_name='סטטוס')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='תאריך פתרון')),
                ('admin_notes', models.TextField(blank=True, verbose_name='הערות צוות טכני')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='מוקצה ל')),
            ],
            options={
                'verbose_name': 'דיווח שגיאה',
                'verbose_name_plural': 'דיווחי שגיאות',
                'ordering': ['-created_at'],
            },
        ),
    ]
