# Generated by Django 5.0.13 on 2025-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_academicrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrequest',
            name='lecturer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('in_progress', 'בטיפול'), ('need_update', 'נדרש עדכון'), ('approved', 'מאושר'), ('rejected', 'נדחה')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
