# Generated by Django 5.0.13 on 2025-06-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_academicrequest_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrequest',
            name='assigned_to',
        ),
    ]
