# Generated by Django 5.0.13 on 2025-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_academicrequest_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
