# Generated by Django 4.2.23 on 2025-06-20 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_chathistory_options_alter_chathistory_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='review_started_at',
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='update_requested_at',
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='schedule_attachments/'),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='subject',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='request_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
