# Generated by Django 4.2.23 on 2025-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_error_description_errorreport_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrequest',
            name='secretary_note',
            field=models.TextField(blank=True, help_text='הערות מהמזכירות', null=True),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='lecturer_note',
            field=models.TextField(blank=True, help_text='הערות מהמרצה', null=True),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='secretary_note',
            field=models.TextField(blank=True, help_text='הערות מהמזכירות', null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='secretary_note',
            field=models.TextField(blank=True, help_text='הערות מהמזכירות', null=True),
        ),
        migrations.AlterField(
            model_name='academicrequest',
            name='lecturer_note',
            field=models.TextField(blank=True, help_text='הערות מהמרצה', null=True),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='lecturer_note',
            field=models.TextField(blank=True, help_text='הערות מהמרצה', null=True),
        ),
    ]
