# Generated by Django 4.2.23 on 2025-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_academicrequest_lecturer_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRequest',
        ),
        migrations.AlterField(
            model_name='academicrequest',
            name='request_type',
            field=models.CharField(choices=[('enrollment_confirmation', 'אישורי רישום או ציונים'), ('academic_appeal', 'ערעורים אקדמיים'), ('exam_review', 'בקשות לבדיקת מבחנים'), ('schedule_change', 'שינוי מערכת שעות'), ('administrative', 'בקשות מנהליות')], max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='request_type',
            field=models.CharField(choices=[('שינויי מערכת שעות', 'שינויי מערכת שעות'), ('בקשות הארכת זמן', 'בקשות הארכת זמן')], max_length=255),
        ),
    ]
