# Generated by Django 4.2.23 on 2025-06-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_remove_schedulerequest_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('recommendation_letter', 'בקשה למכתבי המלצה'), ('personal_details_update', 'עדכון פרטים אישיים'), ('certificates_confirmations', 'בקשת תעודות ואישורים'), ('scholarships_financial_aid', 'בקשות מלגות וסיוע כלכלי'), ('academic_status_change', 'בקשת שינוי סטטוס אקדמי'), ('general_manager_inquiry', 'פניה כללית למנהל')], max_length=50)),
                ('request_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='personal_requests/')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('in_progress', 'בטיפול'), ('need_update', 'נדרש עדכון'), ('approved', 'אושר'), ('rejected', 'נדחה')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'בקשה אישית',
                'verbose_name_plural': 'בקשות אישיות',
                'ordering': ['-created_at'],
            },
        ),
    ]
