# Generated by Django 4.2.23 on 2025-06-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_personalrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorreport',
            old_name='error_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='errorreport',
            name='error_media',
        ),
        migrations.RemoveField(
            model_name='errorreport',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='personalrequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='personalrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='personalrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='personalrequest',
            name='selected_lecturer',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='error_reports/', verbose_name='קובץ מצורף'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='page_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL של הדף'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='priority',
            field=models.CharField(choices=[('low', 'נמוכה - לא דחוף'), ('medium', 'בינונית - יש זמן'), ('high', 'גבוהה - דחוף'), ('critical', 'קריטי - חוסם עבודה')], default='medium', max_length=10, verbose_name='עדיפות'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_error_reports', to=settings.AUTH_USER_MODEL, verbose_name='משתמש מדווח'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='הערות פתרון'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='הערות מנהל'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_error_reports', to=settings.AUTH_USER_MODEL, verbose_name='מוקצה ל'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='error_type',
            field=models.CharField(choices=[('syntax', 'שגיאת תחביר (Syntax)'), ('logic', 'שגיאה לוגית'), ('runtime', 'שגיאת ריצה'), ('ui', 'בעיה בממשק משתמש (UI/UX)'), ('performance', 'בעיית ביצועים'), ('login', 'בעיית התחברות'), ('notification', 'התראות לא נשלחות'), ('database', 'בעיית מסד נתונים'), ('security', 'בעיית אבטחה'), ('other', 'אחר')], max_length=20, verbose_name='סוג השגיאה'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='reporter_email',
            field=models.EmailField(max_length=254, verbose_name='אימייל המדווח'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='reporter_name',
            field=models.CharField(max_length=100, verbose_name='שם המדווח'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='status',
            field=models.CharField(choices=[('new', 'חדש'), ('in_progress', 'בטיפול'), ('resolved', 'נפתר'), ('closed', 'סגור'), ('duplicate', 'כפילות'), ('invalid', 'לא תקף')], default='new', max_length=15, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון אחרון'),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='personal_requests/'),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='request_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='request_type',
            field=models.CharField(choices=[('recommendation_letter', 'בקשה למכתבי המלצה'), ('personal_details_update', 'עדכון פרטים אישיים'), ('certificates_confirmations', 'בקשת תעודות ואישורים'), ('scholarships_financial_aid', 'בקשות מלגות וסיוע כלכלי'), ('academic_status_change', 'בקשת שינוי סטטוס אקדמי'), ('general_manager_inquiry', 'פניה כללית למנהל')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('in_progress', 'בטיפול'), ('need_update', 'נדרש עדכון'), ('approved', 'אושר'), ('rejected', 'נדחה')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ErrorReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='תגובה')),
                ('is_internal', models.BooleanField(default=False, verbose_name='תגובה פנימית')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='כותב התגובה')),
                ('error_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.errorreport', verbose_name='דיווח שגיאה')),
            ],
            options={
                'verbose_name': 'תגובה על דיווח שגיאה',
                'verbose_name_plural': 'תגובות על דיווחי שגיאות',
                'ordering': ['created_at'],
            },
        ),
    ]
