# Generated by Django 4.2.23 on 2025-06-23 10:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_academicrequest_secretary_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrequest',
            name='lecturer_file',
            field=models.FileField(blank=True, help_text='קובץ שמועלה על ידי המרצה', null=True, upload_to=blog.models.lecturer_upload_path),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='lecturer_file_name',
            field=models.CharField(blank=True, help_text='שם המקורי של הקובץ מהמרצה', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='lecturer_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='מתי המרצה העלה את הקובץ', null=True),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='secretary_file',
            field=models.FileField(blank=True, help_text='קובץ שמועלה על ידי המזכירות', null=True, upload_to=blog.models.secretary_upload_path),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='secretary_file_name',
            field=models.CharField(blank=True, help_text='שם המקורי של הקובץ מהמזכירות', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='secretary_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='מתי המזכירות העלתה את הקובץ', null=True),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='lecturer_file',
            field=models.FileField(blank=True, help_text='קובץ שמועלה על ידי המרצה', null=True, upload_to=blog.models.lecturer_upload_path),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='lecturer_file_name',
            field=models.CharField(blank=True, help_text='שם המקורי של הקובץ מהמרצה', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='lecturer_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='מתי המרצה העלה את הקובץ', null=True),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='secretary_file',
            field=models.FileField(blank=True, help_text='קובץ שמועלה על ידי המזכירות', null=True, upload_to=blog.models.secretary_upload_path),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='secretary_file_name',
            field=models.CharField(blank=True, help_text='שם המקורי של הקובץ מהמזכירות', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalrequest',
            name='secretary_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='מתי המזכירות העלתה את הקובץ', null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='lecturer_file',
            field=models.FileField(blank=True, help_text='קובץ שמועלה על ידי המרצה', null=True, upload_to=blog.models.lecturer_upload_path),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='lecturer_file_name',
            field=models.CharField(blank=True, help_text='שם המקורי של הקובץ מהמרצה', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='lecturer_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='מתי המרצה העלה את הקובץ', null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='secretary_file',
            field=models.FileField(blank=True, help_text='קובץ שמועלה על ידי המזכירות', null=True, upload_to=blog.models.secretary_upload_path),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='secretary_file_name',
            field=models.CharField(blank=True, help_text='שם המקורי של הקובץ מהמזכירות', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='secretary_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='מתי המזכירות העלתה את הקובץ', null=True),
        ),
    ]
