# Generated by Django 4.2.23 on 2025-06-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_approved_alter_lecturerprofile_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
